wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1709650458.652402
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.14.0
      6: 4.36.2
      8:
      - 5
always_save_checkpoint:
  desc: null
  value: true
backend:
  desc: null
  value: nccl
batch_size:
  desc: null
  value: 12
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
bias:
  desc: null
  value: false
block_size:
  desc: null
  value: 1024
compile:
  desc: null
  value: false
dataset:
  desc: null
  value: openwebtext
decay_lr:
  desc: null
  value: true
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.0
dtype:
  desc: null
  value: bfloat16
eval_interval:
  desc: null
  value: 1000
eval_iters:
  desc: null
  value: 200
eval_only:
  desc: null
  value: false
grad_clip:
  desc: null
  value: 1.0
gradient_accumulation_steps:
  desc: null
  value: 40
init_from:
  desc: null
  value: scratch
learning_rate:
  desc: null
  value: 0.0006
log_interval:
  desc: null
  value: 10
lr_decay_iters:
  desc: null
  value: 600000
max_iters:
  desc: null
  value: 600000
min_lr:
  desc: null
  value: 6.0e-05
n_embd:
  desc: null
  value: 768
n_head:
  desc: null
  value: 12
n_layer:
  desc: null
  value: 12
out_dir:
  desc: null
  value: out
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: owt
wandb_run_name:
  desc: null
  value: gpt2-124M
warmup_iters:
  desc: null
  value: 2000
weight_decay:
  desc: null
  value: 0.1
